services:
  # サービス名（任意ですが、今回は推論APIなので api とします）
  api:
    # どのディレクトリの Dockerfile を使ってビルドするか（ . は「ここ」という意味）
    build: .
    # 起動した時のコンテナのわかりやすい名前
    container_name: churn-api-prod
    # ポートの紐付け（ "ホスト側のPCのポート : コンテナ内部のポート" ）
    ports:
      - "8000:8000"
    # 万が一サーバーが落ちても、自動で再起動して復旧させる本番用の最強設定
    restart: always